GET https://wakfu.cdn.ankama.com/gamedata/1.86.4.35/resourceTypes.json
#####################################################################
GET https://wakfu.cdn.ankama.com/gamedata/1.86.4.35/resources.json
