GET http://localhost:3000/items?itemTypeId=114&locale=fr&page=2&take=10&order=ASC&orderBy=definition.item.id HTTP/2
Content-Type: application/json
###
GET http://localhost:3000/items?itemTypeId=114&locale=en&page=1&take=10&title=hamm&order=ASC&orderBy=definition.item.id
Content-Type: application/json
###
GET http://localhost:3000/items?&locale=en&page=1&take=10&title=hamm&order=ASC&orderBy=definition.item.id
Content-Type: application/json
###
GET https://wakfu.cdn.ankama.com/gamedata/config.json
### RESOURCES
GET https://wakfu.cdn.ankama.com/gamedata/1.86.4.35/resources.json
Content-Type: application/json
###
GET https://wakfu.cdn.ankama.com/gamedata/1.86.4.35/itemProperties.json
Content-Type: application/json
###
GET https://wakfu.cdn.ankama.com/gamedata/1.86.4.35/itemTypes.json
Content-Type: application/json
### ACTIONS
GET https://wakfu.cdn.ankama.com/gamedata/1.86.4.35/actions.json
Content-Type: application/json
###
GET https://wakfu.cdn.ankama.com/gamedata/1.86.4.35/items.json
Content-Type: application/json
###
GET http://localhost:3000/items/fr?order=ASC&orderBy=definition.item.id&itemTypeId=134&page=1&take=10
Content-Type: application/json
