GET https://wakfu.cdn.ankama.com/gamedata/config.json
### RESOURCES
GET https://wakfu.cdn.ankama.com/gamedata/1.86.4.35/resources.json
Content-Type: application/json
### RESOURCES TYPES
GET https://wakfu.cdn.ankama.com/gamedata/1.86.4.35/resourceTypes.json
Content-Type: application/json
###
GET https://wakfu.cdn.ankama.com/gamedata/1.86.4.35/itemProperties.json
Content-Type: application/json
###
GET https://wakfu.cdn.ankama.com/gamedata/1.86.4.35/itemTypes.json
Content-Type: application/json
### ACTIONS
GET https://wakfu.cdn.ankama.com/gamedata/1.86.4.35/actions.json
Content-Type: application/json
###
GET https://wakfu.cdn.ankama.com/gamedata/1.86.4.35/items.json
Content-Type: application/json
###
GET https://wakfu.cdn.ankama.com/gamedata/1.86.4.35/equipmentItemTypes.json
Content-Type: application/json
###
GET htps://wakfu.cdn.ankama.com/gamedata/1.86.4.35/recipeCategories.json
Content-Type: application/json
###
GET https://wakfu.cdn.ankama.com/gamedata/1.86.4.35/recipeIngredients.json
Content-Type: application/json
###
GET https://wakfu.cdn.ankama.com/gamedata/1.86.4.35/collectibleResources.json
Content-Type: application/json
###
GET https://wakfu.cdn.ankama.com/gamedata/1.86.4.35/harvestLoots.json
Content-Type: application/json
###
GET http://localhost:3000/items/fr?order=ASC&orderBy=definition.item.id&itemTypeId=134&page=1&take=10
Content-Type: application/json
###
GET http://localhost:3000/resources/fr?order=ASC&orderBy=definition.id&page=1&take=100
Content-Type: application/json
###
GET http://localhost:3000/actions/en?order=ASC&orderBy=definition.id&page=1&take=10
Content-Type: application/json
